### PR TITLE
Enable the Travis CI Continuous Integration Service

### PR DESCRIPTION
**Pull request by DaSourcerer**
This PR provides a complete configuration for the [Travis CI](https://travis-ci.org) service which provides automated test runs on every push (or PR) to the repository. Signup is free and can be done through Github.

Enabling Travis CI for this repository will allow to detect possible problems early. FWIW, the build badge is going to look like this after pulling:
Build Status

The last (i.e. the first) build results can be seen [here](https://travis-ci.org/DaSourcerer/jBBCode/builds/55289998).

PS: This sorta depends on/includes #46

### CODE REVIEW

**Comment by shmax** [comment]
:+1:

**Comment by Art4** [comment]
:+1: Great!

**Comment by jbowens** [comment]
Thanks

**Comment by Kubo2** [comment]
@DaSourcerer :100:

**Comment by DaSourcerer** [comment]
@Kubo2: I take it, that's a sign of approval? :wink:

@jbowens: Any estimate on when you'll be able to sign up with Travis CI? I've made some progress with the tests. Would be great if they'll be put to good use soon :smile:

**Comment by Kubo2** [comment]
@DaSourcerer That sign is something much better than +1 :smile:

**Comment by DaSourcerer** [comment]
@Kubo2 Well, now I'm curious to know what you've got to say about #53 :laughing:

**Comment by DaSourcerer** [comment]
@jbowens Couldn't help but notice you're now signed up with Travis. Gj! :+1:

**Comment by jbowens** [comment]
@DaSourcerer yeah, I had added the repo to Travis several days ago, but it wasn't picked up until a recent merge.

**Pull request merged**
